server:
  port: 8080

spring:
  application:
    name: cloud-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id:  cloud-order-service
          uri: lb://cloud-order-service
          predicates:
            - Path=/api/orderService/**
          filters:
            - StripPrefix=2